<script setup>
import { getTicketEventLabel, getTicketStatusLabel } from '@/utils/tickets'
defineProps({ events:{type:Array,default:()=>[]} })
const formatter = new Intl.DateTimeFormat('es-CO',{dateStyle:'medium',timeStyle:'short'})
const date = value => { const parsed=new Date(value); return value && !Number.isNaN(parsed.getTime()) ? formatter.format(parsed) : 'Fecha no disponible' }
const metadataRows = event => {
  const metadata=event.metadata || {}; const labels={diagnosis:'Diagnóstico',solution:'Solución',notes:'Notas',source:'Origen',priority:'Prioridad'}
  return Object.entries(labels).filter(([key]) => metadata[key]).map(([key,label]) => ({label,value:metadata[key]}))
}
</script>
<template><section class="timeline-card"><header><h2>Línea de tiempo</h2><p>Historial persistido de acciones sobre el ticket.</p></header><div v-if="!events.length" class="empty">No hay eventos registrados.</div><ol v-else><li v-for="event in events" :key="event.id"><span class="marker"></span><article><div class="top"><div><h3>{{ getTicketEventLabel(event.event_type) }}</h3><p>{{ event.description }}</p></div><time>{{ date(event.created_at) }}</time></div><div v-if="event.old_status || event.new_status" class="change"><span v-if="event.old_status">{{ getTicketStatusLabel(event.old_status) }}</span><b v-if="event.old_status && event.new_status">→</b><strong v-if="event.new_status">{{ getTicketStatusLabel(event.new_status) }}</strong></div><p v-if="event.reason" class="reason"><b>Motivo:</b> {{ event.reason }}</p><dl v-if="metadataRows(event).length"><div v-for="row in metadataRows(event)" :key="row.label"><dt>{{ row.label }}</dt><dd>{{ row.value }}</dd></div></dl><footer><span>Realizado por</span><strong>{{ event.user?.name || 'Usuario no disponible' }}</strong><small v-if="event.user?.email">{{ event.user.email }}</small></footer></article></li></ol></section></template>
<style scoped>
.timeline-card{background:#fff;border:1px solid var(--color-border);border-radius:var(--radius-lg);padding:24px}.timeline-card>header h2{margin:0 0 5px;font-size:18px}.timeline-card>header p{margin:0;color:var(--color-text-muted);font-size:13px}.empty{padding:42px 0;text-align:center;color:var(--color-text-muted)}ol{list-style:none;margin:24px 0 0;padding:0}li{position:relative;display:grid;grid-template-columns:22px minmax(0,1fr);gap:12px;padding-bottom:22px}li:not(:last-child)::before{content:'';position:absolute;left:6px;top:14px;bottom:0;width:2px;background:#e2e8f0}.marker{z-index:1;margin-top:6px;width:13px;height:13px;border:3px solid #dbeafe;border-radius:50%;background:var(--color-primary)}article{min-width:0;padding:16px 18px;border:1px solid #e8edf3;border-radius:10px;background:#fbfdff}.top{display:flex;justify-content:space-between;gap:14px}.top h3{margin:0;font-size:14px}.top p{margin:4px 0 0;color:var(--color-text-muted);font-size:13px}.top time{white-space:nowrap;color:var(--color-text-subtle);font-size:12px}.change{display:flex;align-items:center;gap:8px;margin-top:12px;font-size:12px;color:#64748b}.change strong{color:var(--color-primary)}.reason{margin:12px 0 0;font-size:13px;color:#475569;white-space:pre-wrap}dl{display:grid;gap:8px;margin:13px 0 0;padding-top:12px;border-top:1px solid #e8edf3}dl div{display:grid;grid-template-columns:100px 1fr;gap:10px}dt{font-size:11px;font-weight:700;color:#64748b}dd{margin:0;font-size:13px;white-space:pre-wrap;overflow-wrap:anywhere}article footer{display:flex;flex-wrap:wrap;gap:6px;margin-top:14px;color:#94a3b8;font-size:11px}article footer strong{color:#64748b}@media(max-width:560px){.timeline-card{padding:18px}.top{flex-direction:column}.top time{white-space:normal}article{padding:14px}dl div{grid-template-columns:1fr;gap:2px}}
</style>
