<script setup>
import TicketStatusBadge from './TicketStatusBadge.vue'
import TicketPriorityBadge from './TicketPriorityBadge.vue'
import TicketSlaBadge from './TicketSlaBadge.vue'

defineProps({ tickets:{type:Array,default:()=>[]}, loading:Boolean, pagination:{type:Object,required:true}, hasActiveFilters:Boolean, canCreate:Boolean })
const emit = defineEmits(['page-change','clear','create'])
const formatter = new Intl.DateTimeFormat('es-CO',{dateStyle:'short',timeStyle:'short'})
const date = value => { if (!value) return 'Sin fecha'; const parsed=new Date(value); return Number.isNaN(parsed.getTime())?'Sin fecha':formatter.format(parsed) }
</script>
<template>
  <section class="panel" aria-label="Listado de tickets" :aria-busy="loading">
    <div class="desktop">
      <table><thead><tr><th>Código</th><th>Ticket</th><th>Estado</th><th>Prioridad</th><th>Activo</th><th>Técnico</th><th>Reportado / SLA</th><th>Acción</th></tr></thead>
      <tbody v-if="loading"><tr v-for="n in 5" :key="n"><td v-for="m in 8" :key="m"><span class="skeleton"></span></td></tr></tbody>
      <tbody v-else-if="tickets.length"><tr v-for="ticket in tickets" :key="ticket.id">
        <td><span class="code">{{ ticket.code || 'Sin código' }}</span><small v-if="ticket.source === 'qr'" class="qr-source">Origen QR</small></td><td><strong class="truncate">{{ ticket.title || 'Sin título' }}</strong><small>{{ ticket.reporter_name || 'Solicitante no informado' }}</small></td>
        <td><TicketStatusBadge :status="ticket.status" /></td><td><TicketPriorityBadge :priority="ticket.priority" /></td>
        <td><strong>{{ ticket.asset?.code || 'Sin activo asociado' }}</strong><small v-if="ticket.asset">{{ ticket.asset.name || 'Sin nombre' }}</small></td>
        <td>{{ ticket.assigned_technician?.name || 'Sin asignar' }}</td><td><span>{{ date(ticket.reported_at) }}</span><TicketSlaBadge :status="ticket.resolution_sla_status" /></td>
        <td><RouterLink class="view" :to="{name:'ticket-detail',params:{id:ticket.id}}">Ver</RouterLink></td>
      </tr></tbody></table>
    </div>
    <div v-if="loading" class="mobile"><article v-for="n in 4" :key="n" class="card"><span class="skeleton wide"></span><span class="skeleton"></span><span class="skeleton wide"></span></article></div>
    <div v-else-if="tickets.length" class="mobile"><article v-for="ticket in tickets" :key="ticket.id" class="card"><span class="code">{{ ticket.code || 'Sin código' }}</span><small v-if="ticket.source === 'qr'" class="qr-source">Origen QR</small><h3>{{ ticket.title || 'Sin título' }}</h3><div class="badges"><TicketStatusBadge :status="ticket.status"/><TicketPriorityBadge :priority="ticket.priority"/></div><dl><div><dt>Técnico</dt><dd>{{ ticket.assigned_technician?.name || 'Sin asignar' }}</dd></div><div><dt>Reportado</dt><dd>{{ date(ticket.reported_at) }}</dd></div><div><dt>SLA resolución</dt><dd><TicketSlaBadge :status="ticket.resolution_sla_status"/></dd></div></dl><RouterLink class="view" :to="{name:'ticket-detail',params:{id:ticket.id}}">Ver ticket</RouterLink></article></div>
    <div v-if="!loading && !tickets.length" class="empty"><h3>{{ hasActiveFilters ? 'No encontramos tickets con los filtros seleccionados.' : 'Aún no hay tickets registrados.' }}</h3><p>{{ hasActiveFilters ? 'Modifica la búsqueda o restablece los filtros.' : 'Los nuevos casos de soporte aparecerán en esta bandeja.' }}</p><button v-if="hasActiveFilters" type="button" @click="emit('clear')">Limpiar filtros</button><button v-else-if="canCreate" type="button" @click="emit('create')">Crear primer ticket</button></div>
    <footer v-if="!loading && pagination.total>0"><span>Mostrando {{ pagination.from || 0 }}–{{ pagination.to || 0 }} de {{ pagination.total }}</span><nav aria-label="Paginación de tickets"><button :disabled="pagination.current_page<=1" @click="emit('page-change',pagination.current_page-1)">Anterior</button><span>Página <strong>{{ pagination.current_page }}</strong> de <strong>{{ pagination.last_page }}</strong></span><button :disabled="pagination.current_page>=pagination.last_page" @click="emit('page-change',pagination.current_page+1)">Siguiente</button></nav></footer>
  </section>
</template>
<style scoped>
.panel{background:#fff;border:1px solid var(--color-border);border-radius:var(--radius-lg);box-shadow:var(--shadow-sm);overflow:hidden}.desktop{overflow-x:auto}table{width:100%;border-collapse:collapse;font-size:13px;text-align:left}th{padding:13px 14px;background:#f8fafc;border-bottom:1px solid var(--color-border);color:#64748b;font-size:11px;text-transform:uppercase;letter-spacing:.04em;white-space:nowrap}td{padding:15px 14px;border-bottom:1px solid #f1f5f9;vertical-align:middle}tbody tr:hover{background:#f8fafc}td strong,td span{display:block}small{display:block;margin-top:3px;color:#64748b}.truncate{max-width:240px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.code{font-family:ui-monospace,monospace;color:var(--color-primary);font-weight:700;white-space:nowrap}.qr-source{color:#475569;font-weight:700}.view{display:inline-flex;min-height:36px;align-items:center;padding:0 12px;border:1px solid #bfdbfe;border-radius:7px;color:var(--color-primary);font-weight:650;white-space:nowrap}.view:focus-visible,button:focus-visible{outline:3px solid rgba(37,99,235,.2)}.skeleton{display:block;width:70px;height:13px;border-radius:5px;background:linear-gradient(90deg,#e2e8f0,#f8fafc,#e2e8f0);background-size:200%;animation:pulse 1.3s infinite}.wide{width:80%}@keyframes pulse{to{background-position:-200% 0}}.empty{text-align:center;padding:52px 20px}.empty h3{font-size:16px}.empty p{margin:6px 0 18px;color:#64748b}.empty button{padding:9px 14px;border:0;border-radius:8px;background:var(--color-primary);color:#fff;font-weight:650;cursor:pointer}footer{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:15px 18px;color:#64748b;font-size:13px}nav{display:flex;align-items:center;gap:12px}nav button{padding:8px 11px;border:1px solid var(--color-border);border-radius:7px;background:#fff;color:#334155;cursor:pointer}nav button:disabled{opacity:.45;cursor:not-allowed}.mobile{display:none}.card{padding:18px;border-bottom:1px solid var(--color-border);display:grid;gap:11px}.card h3{font-size:15px;overflow-wrap:anywhere}.badges{display:flex;gap:8px;flex-wrap:wrap}.card dl{display:grid;gap:8px}.card dl div{display:flex;justify-content:space-between;gap:12px}.card dt{color:#64748b;font-size:12px}.card dd{text-align:right;font-size:13px}.card .view{justify-content:center}@media(max-width:1050px){th:nth-child(5),td:nth-child(5){display:none}}@media(max-width:720px){.desktop{display:none}.mobile{display:block}footer{flex-direction:column;align-items:stretch}footer>span{text-align:center}nav{justify-content:space-between}.empty{padding:38px 18px}}
</style>
